name: Build and test pkg

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and configure Poetry
      run: |
        pip install poetry
        poetry --version
        poetry config virtualenvs.in-project true
    
    - name: Cache the virtualenv
      uses: actions/cache@v3
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install project dependencies
      run: |
        poetry install

    - name: Run tests and collect coverage
      run: |
        poetry run pytest --cov -v -s
#        poetry run pytest --cov -v -s -n auto
#        poetry run coverage run -m pytest -v -s
#        poetry run coverage report
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./.coverage
        verbose: true
