name: Build and test pkg

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry --version
    
    - name: Install project dependencies
      run: |
        poetry install

    - name: Run tests and collect coverage
      run: |
        poetry run coverage run -m pytest -v -s
        poetry run coverage report
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
