name: Test

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        #        os: [Ubuntu, Windows, macOS]
        os: [Ubuntu]
        python-version: ["3.10", "3.11", "3.12"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
      #          - os: Windows
      #            image: windows-2022
      #          - os: macOS
      #            image: macos-12
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get full Python version
        id: full-python-version
        run: echo version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))") >> $GITHUB_OUTPUT

      - name: Install and configure Poetry
        run: |
          pip install poetry
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install project dependencies
        run: |
          poetry install --with dev

      - name: Run tests with Numba enabled
        run: |
          poetry run pytest -v -s
      
      - name: Run tests with Numba disabled and collect coverage
        continue-on-error: true
        run: |
          export NUMBA_DISABLE_JIT=1
          poetry run pytest --cov -v -s --cov-report=xml --junitxml=junit.xml -o junit_family=legacy
          poetry run coverage report --omit="tests/*"
          
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.10' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
          
      - name: Upload test results to Codecov
        if: ${{ matrix.python-version == '3.10' && !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
