name: Test

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.python-version }}-${{ matrix.resolution }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        resolution: ["lowest-direct", "highest"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        exclude:
          - python-version: "3.13"
            resolution: "lowest-direct" #numba 0.60 requires python < 3.13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        run: |
          pip install uv
          uv --version

      - name: Install project dependencies
        run: |
          uv sync --resolution ${{ matrix.resolution }}

      - name: Run tests with Numba enabled
        run: |
          uv run --frozen pytest
      
      - name: Run tests with Numba disabled and collect coverage
        continue-on-error: true
        run: |
          export NUMBA_DISABLE_JIT=1
          uv run --frozen pytest --cov -v -s --cov-report=xml --junitxml=junit.xml -o junit_family=legacy
          uv run --frozen coverage report --omit="tests/*"
          
      - name: Upload coverage to Codecov
        if: ${{ matrix.python-version == '3.12' && matrix.resolution == 'highest' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: false
          
      - name: Upload test results to Codecov
        if: ${{ matrix.python-version == '3.12' && matrix.resolution == 'highest' && !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
